version: "3.8"
services:
  node_app:
    restart: "no"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env
    container_name: tt_erp_be
    networks:
      - erp_network
    ports:
      - "8080:8080"

networks:
  erp_network: